services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: autoservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d autoservice"]
      interval: 5s
      timeout: 5s
      retries: 5
#
#  app:
#    build: .
#    depends_on:
#      postgres:
#        condition: service_healthy
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/autoservice
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#      SPRING_LIQUIBASE_ENABLED: "true"
#      SPRING_JPA_HIBERNATE_DDL_AUTO: "create-drop"
#      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
#      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
#      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
#      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./logs:/app/logs
#      - ./config:/app/config
#
#
#  swagger:
#    image: swaggerapi/swagger-ui
#    ports:
#      - "8081:8080"
#    environment:
#      API_URL: http://app:8080/v3/api-docs
#    depends_on:
#      - app

volumes:
  postgres-data: